parse_config:
  zmk_keycode_map:
    LCTRL: ⌃
    LALT: ⎇
    LGUI: ⌘
    LSHFT: ⇧
    RCTRL: ⌃
    LEFT_CONTROL: ⌃
    LEFT_ALT: ⎇
    LEFT_GUI: ⌘
    LEFT_SHFT: ⇧
    RALT: ⎇
    RGUI: ⌘
    RSHFT: ⇧
    RIGHT_CONTROL: ⌃
    RIGHT_ALT: ⎇
    RIGHT_GUI: ⌘
    RIGHT_SHFT: ⇧
    LEFT: ←
    RIGHT: →
    UP: ↑
    DOWN: ↓
    TAB: ↹
    RETURN: '⏎'
    ESCAPE: '⎋'
    C_REWIND: '⏮'
    C_FAST_FORWARD: '⏭'
    C_PAUSE: '⏯'
    C_MUTE: "VOL\nMUTE"
    C_VOLUME_DOWN: "VOL\nDOWN"
    C_VOLUME_UP: "VOL\nUP"
    C_BRIGHTNESS_DEC: '☀↓'
    C_BRIGHTNESS_INC: '☀↑'
    LA(LEFT): ↞
    LA(RIGHT): ↠
    LG(LEFT): ⇤
    LG(RIGHT): ⇥
    'LS(LC(LG(LALT)))': 'HYPER'
    'RS(RC(RG(RALT)))': 'HYPER'
    'LC(LG(LALT))': 'MEH'
    'RC(RG(RALT))': 'MEH'
    'LG(Q)': '⌘Q'
    'LG(W)': '⌘W'
    'LG(GRAVE)': '⌘`'
    'LG(Z)': '⌘Z'
    'LG(X)': '⌘X'
    'LG(C)': '⌘C'
    'LG(V)': '⌘V'
    'LC(TAB)': '⌃↹'
    'LS(LC(TAB))': '⌃⇧↹'
